// THIS FILE IS AUTO GENERATED
// DO NOT EDIT MANUALLY

// GENERATED BY scripts/codegen/countries-index.mjs
// TO REGEN RUN `yarn zx scripts/codegen/countries-index.mjs`

import africadosul from "./africadosul.png";
import angola from "./angola.png";
import argelia from "./argelia.png";
import benim from "./benim.png";
import botswana from "./botswana.png";
import burkinafaso from "./burkinafaso.png";
import burundi from "./burundi.png";
import caboverde from "./caboverde.png";
import camaroes from "./camaroes.png";
import chade from "./chade.png";
import comores from "./comores.png";
import costadomarfim from "./costadomarfim.png";
import djibouti from "./djibouti.png";
import egito from "./egito.png";
import eritreia from "./eritreia.png";
import etiopia from "./etiopia.png";
import gabao from "./gabao.png";
import gambia from "./gambia.png";
import gana from "./gana.png";
import guinebissau from "./guinebissau.png";
import guineequatorial from "./guineequatorial.png";
import guine from "./guine.png";
import lesoto from "./lesoto.png";
import liberia from "./liberia.png";
import libia from "./libia.png";
import madagascar from "./madagascar.png";
import malawi from "./malawi.png";
import mali from "./mali.png";
import marrocos from "./marrocos.png";
import mauricia from "./mauricia.png";
import mauritania from "./mauritania.png";
import mocambique from "./mocambique.png";
import namibia from "./namibia.png";
import nigeria from "./nigeria.png";
import niger from "./niger.png";
import quenia from "./quenia.png";
import republicacentroafricana from "./republicacentroafricana.png";
import republicademocraticadocongo from "./republicademocraticadocongo.png";
import republicadocongo from "./republicadocongo.png";
import ruanda from "./ruanda.png";
import saotomeeprincipe from "./saotomeeprincipe.png";
import senegal from "./senegal.png";
import serraleoa from "./serraleoa.png";
import seychelles from "./seychelles.png";
import somalia from "./somalia.png";
import suazilandia from "./suazilandia.png";
import sudaodosul from "./sudaodosul.png";
import sudao from "./sudao.png";
import tanzania from "./tanzania.png";
import togo from "./togo.png";
import tunisia from "./tunisia.png";
import uganda from "./uganda.png";
import zambia from "./zambia.png";
import zimbabue from "./zimbabue.png";

export {
  africadosul,
  angola,
  argelia,
  benim,
  botswana,
  burkinafaso,
  burundi,
  caboverde,
  camaroes,
  chade,
  comores,
  costadomarfim,
  djibouti,
  egito,
  eritreia,
  etiopia,
  gabao,
  gambia,
  gana,
  guinebissau,
  guineequatorial,
  guine,
  lesoto,
  liberia,
  libia,
  madagascar,
  malawi,
  mali,
  marrocos,
  mauricia,
  mauritania,
  mocambique,
  namibia,
  nigeria,
  niger,
  quenia,
  republicacentroafricana,
  republicademocraticadocongo,
  republicadocongo,
  ruanda,
  saotomeeprincipe,
  senegal,
  serraleoa,
  seychelles,
  somalia,
  suazilandia,
  sudaodosul,
  sudao,
  tanzania,
  togo,
  tunisia,
  uganda,
  zambia,
  zimbabue,
};

