// THIS FILE IS AUTO GENERATED
// DO NOT EDIT MANUALLY

// GENERATED BY scripts/codegen/flags-index.mjs
// TO REGEN RUN `yarn zx scripts/codegen/flags-index.mjs`

import afeganistao from "./afeganistao.png";
import africadosul from "./africadosul.png";
import albania from "./albania.png";
import alemanha from "./alemanha.png";
import andorra from "./andorra.png";
import angola from "./angola.png";
import antiguaebarbuda from "./antiguaebarbuda.png";
import arabiasaudita from "./arabiasaudita.png";
import argelia from "./argelia.png";
import argentina from "./argentina.png";
import armenia from "./armenia.png";
import australia from "./australia.png";
import austria from "./austria.png";
import azerbaijao from "./azerbaijao.png";
import bahamas from "./bahamas.png";
import bahrein from "./bahrein.png";
import bangladesh from "./bangladesh.png";
import barbados from "./barbados.png";
import belgica from "./belgica.png";
import belize from "./belize.png";
import benim from "./benim.png";
import bielorussia from "./bielorussia.png";
import birmania from "./birmania.png";
import bolivia from "./bolivia.png";
import bosniaeherzegovina from "./bosniaeherzegovina.png";
import botswana from "./botswana.png";
import brasil from "./brasil.png";
import brunei from "./brunei.png";
import bulgaria from "./bulgaria.png";
import burkinafaso from "./burkinafaso.png";
import burundi from "./burundi.png";
import butao from "./butao.png";
import caboverde from "./caboverde.png";
import camaroes from "./camaroes.png";
import camboja from "./camboja.png";
import canada from "./canada.png";
import catar from "./catar.png";
import cazaquistao from "./cazaquistao.png";
import chade from "./chade.png";
import chile from "./chile.png";
import china from "./china.png";
import chipre from "./chipre.png";
import colombia from "./colombia.png";
import comores from "./comores.png";
import coreiadonorte from "./coreiadonorte.png";
import coreiadosul from "./coreiadosul.png";
import costadomarfim from "./costadomarfim.png";
import costarica from "./costarica.png";
import croacia from "./croacia.png";
import cuba from "./cuba.png";
import dinamarca from "./dinamarca.png";
import djibouti from "./djibouti.png";
import dominica from "./dominica.png";
import egito from "./egito.png";
import elsalvador from "./elsalvador.png";
import emiradosarabesunidos from "./emiradosarabesunidos.png";
import equador from "./equador.png";
import eritreia from "./eritreia.png";
import eslovaquia from "./eslovaquia.png";
import eslovenia from "./eslovenia.png";
import espanha from "./espanha.png";
import estadosunidos from "./estadosunidos.png";
import estonia from "./estonia.png";
import etiopia from "./etiopia.png";
import fiji from "./fiji.png";
import filipinas from "./filipinas.png";
import finlandia from "./finlandia.png";
import franca from "./franca.png";
import gabao from "./gabao.png";
import gambia from "./gambia.png";
import gana from "./gana.png";
import georgia from "./georgia.png";
import granada from "./granada.png";
import grecia from "./grecia.png";
import guatemala from "./guatemala.png";
import guiana from "./guiana.png";
import guinebissau from "./guinebissau.png";
import guineequatorial from "./guineequatorial.png";
import guine from "./guine.png";
import haiti from "./haiti.png";
import honduras from "./honduras.png";
import hungria from "./hungria.png";
import iemen from "./iemen.png";
import ilhasmarshall from "./ilhasmarshall.png";
import ilhassalomao from "./ilhassalomao.png";
import india from "./india.png";
import indonesia from "./indonesia.png";
import iran from "./iran.png";
import iraque from "./iraque.png";
import irlanda from "./irlanda.png";
import islandia from "./islandia.png";
import israel from "./israel.png";
import italia from "./italia.png";
import jamaica from "./jamaica.png";
import japao from "./japao.png";
import jordania from "./jordania.png";
import kiribati from "./kiribati.png";
import kosovo from "./kosovo.png";
import kuwait from "./kuwait.png";
import laos from "./laos.png";
import lesoto from "./lesoto.png";
import letonia from "./letonia.png";
import libano from "./libano.png";
import liberia from "./liberia.png";
import libia from "./libia.png";
import liechtenstein from "./liechtenstein.png";
import lituania from "./lituania.png";
import luxemburgo from "./luxemburgo.png";
import macedoniadonorte from "./macedoniadonorte.png";
import madagascar from "./madagascar.png";
import malasia from "./malasia.png";
import malawi from "./malawi.png";
import maldivas from "./maldivas.png";
import mali from "./mali.png";
import malta from "./malta.png";
import marrocos from "./marrocos.png";
import mauricia from "./mauricia.png";
import mauritania from "./mauritania.png";
import mexico from "./mexico.png";
import micronesia from "./micronesia.png";
import mocambique from "./mocambique.png";
import moldavia from "./moldavia.png";
import monaco from "./monaco.png";
import mongolia from "./mongolia.png";
import montenegro from "./montenegro.png";
import namibia from "./namibia.png";
import nauru from "./nauru.png";
import nepal from "./nepal.png";
import nicaragua from "./nicaragua.png";
import nigeria from "./nigeria.png";
import niger from "./niger.png";
import noruega from "./noruega.png";
import novazelandia from "./novazelandia.png";
import oma from "./oma.png";
import paisesbaixos from "./paisesbaixos.png";
import palau from "./palau.png";
import panama from "./panama.png";
import papuanovaguine from "./papuanovaguine.png";
import paquistao from "./paquistao.png";
import paraguai from "./paraguai.png";
import peru from "./peru.png";
import polonia from "./polonia.png";
import portugal from "./portugal.png";
import quenia from "./quenia.png";
import quirguistao from "./quirguistao.png";
import reinounido from "./reinounido.png";
import republicacentroafricana from "./republicacentroafricana.png";
import republicademocraticadocongo from "./republicademocraticadocongo.png";
import republicadocongo from "./republicadocongo.png";
import republicadominicana from "./republicadominicana.png";
import republicatcheca from "./republicatcheca.png";
import romenia from "./romenia.png";
import ruanda from "./ruanda.png";
import russia from "./russia.png";
import samoa from "./samoa.png";
import sanmarino from "./sanmarino.png";
import santalucia from "./santalucia.png";
import saocristovaoenevis from "./saocristovaoenevis.png";
import saotomeeprincipe from "./saotomeeprincipe.png";
import saovicenteegranadinas from "./saovicenteegranadinas.png";
import senegal from "./senegal.png";
import serraleoa from "./serraleoa.png";
import servia from "./servia.png";
import seychelles from "./seychelles.png";
import singapura from "./singapura.png";
import siria from "./siria.png";
import somalia from "./somalia.png";
import srilanka from "./srilanka.png";
import suazilandia from "./suazilandia.png";
import sudaodosul from "./sudaodosul.png";
import sudao from "./sudao.png";
import suecia from "./suecia.png";
import suica from "./suica.png";
import suriname from "./suriname.png";
import tailandia from "./tailandia.png";
import taiwan from "./taiwan.png";
import tajiquistao from "./tajiquistao.png";
import tanzania from "./tanzania.png";
import timorleste from "./timorleste.png";
import togo from "./togo.png";
import tonga from "./tonga.png";
import trinidadetobago from "./trinidadetobago.png";
import tunisia from "./tunisia.png";
import turcomenistao from "./turcomenistao.png";
import turquia from "./turquia.png";
import tuvalu from "./tuvalu.png";
import ucrania from "./ucrania.png";
import uganda from "./uganda.png";
import uruguai from "./uruguai.png";
import uzbequistao from "./uzbequistao.png";
import vanuatu from "./vanuatu.png";
import vaticano from "./vaticano.png";
import venezuela from "./venezuela.png";
import vietna from "./vietna.png";
import zambia from "./zambia.png";
import zimbabue from "./zimbabue.png";

export {
  afeganistao,
  africadosul,
  albania,
  alemanha,
  andorra,
  angola,
  antiguaebarbuda,
  arabiasaudita,
  argelia,
  argentina,
  armenia,
  australia,
  austria,
  azerbaijao,
  bahamas,
  bahrein,
  bangladesh,
  barbados,
  belgica,
  belize,
  benim,
  bielorussia,
  birmania,
  bolivia,
  bosniaeherzegovina,
  botswana,
  brasil,
  brunei,
  bulgaria,
  burkinafaso,
  burundi,
  butao,
  caboverde,
  camaroes,
  camboja,
  canada,
  catar,
  cazaquistao,
  chade,
  chile,
  china,
  chipre,
  colombia,
  comores,
  coreiadonorte,
  coreiadosul,
  costadomarfim,
  costarica,
  croacia,
  cuba,
  dinamarca,
  djibouti,
  dominica,
  egito,
  elsalvador,
  emiradosarabesunidos,
  equador,
  eritreia,
  eslovaquia,
  eslovenia,
  espanha,
  estadosunidos,
  estonia,
  etiopia,
  fiji,
  filipinas,
  finlandia,
  franca,
  gabao,
  gambia,
  gana,
  georgia,
  granada,
  grecia,
  guatemala,
  guiana,
  guinebissau,
  guineequatorial,
  guine,
  haiti,
  honduras,
  hungria,
  iemen,
  ilhasmarshall,
  ilhassalomao,
  india,
  indonesia,
  iran,
  iraque,
  irlanda,
  islandia,
  israel,
  italia,
  jamaica,
  japao,
  jordania,
  kiribati,
  kosovo,
  kuwait,
  laos,
  lesoto,
  letonia,
  libano,
  liberia,
  libia,
  liechtenstein,
  lituania,
  luxemburgo,
  macedoniadonorte,
  madagascar,
  malasia,
  malawi,
  maldivas,
  mali,
  malta,
  marrocos,
  mauricia,
  mauritania,
  mexico,
  micronesia,
  mocambique,
  moldavia,
  monaco,
  mongolia,
  montenegro,
  namibia,
  nauru,
  nepal,
  nicaragua,
  nigeria,
  niger,
  noruega,
  novazelandia,
  oma,
  paisesbaixos,
  palau,
  panama,
  papuanovaguine,
  paquistao,
  paraguai,
  peru,
  polonia,
  portugal,
  quenia,
  quirguistao,
  reinounido,
  republicacentroafricana,
  republicademocraticadocongo,
  republicadocongo,
  republicadominicana,
  republicatcheca,
  romenia,
  ruanda,
  russia,
  samoa,
  sanmarino,
  santalucia,
  saocristovaoenevis,
  saotomeeprincipe,
  saovicenteegranadinas,
  senegal,
  serraleoa,
  servia,
  seychelles,
  singapura,
  siria,
  somalia,
  srilanka,
  suazilandia,
  sudaodosul,
  sudao,
  suecia,
  suica,
  suriname,
  tailandia,
  taiwan,
  tajiquistao,
  tanzania,
  timorleste,
  togo,
  tonga,
  trinidadetobago,
  tunisia,
  turcomenistao,
  turquia,
  tuvalu,
  ucrania,
  uganda,
  uruguai,
  uzbequistao,
  vanuatu,
  vaticano,
  venezuela,
  vietna,
  zambia,
  zimbabue,
};

