// THIS FILE IS AUTO GENERATED
// DO NOT EDIT MANUALLY

// GENERATED BY scripts/codegen/countries-index.mjs
// TO REGEN RUN `yarn zx scripts/codegen/countries-index.mjs`

import afeganistao from "./afeganistao.png";
import arabiasaudita from "./arabiasaudita.png";
import armenia from "./armenia.png";
import azerbaijao from "./azerbaijao.png";
import bahrein from "./bahrein.png";
import bangladesh from "./bangladesh.png";
import birmania from "./birmania.png";
import brunei from "./brunei.png";
import butao from "./butao.png";
import camboja from "./camboja.png";
import catar from "./catar.png";
import cazaquistao from "./cazaquistao.png";
import china from "./china.png";
import chipre from "./chipre.png";
import coreiadonorte from "./coreiadonorte.png";
import coreiadosul from "./coreiadosul.png";
import emiradosarabesunidos from "./emiradosarabesunidos.png";
import filipinas from "./filipinas.png";
import georgia from "./georgia.png";
import iemen from "./iemen.png";
import india from "./india.png";
import indonesia from "./indonesia.png";
import iran from "./iran.png";
import iraque from "./iraque.png";
import israel from "./israel.png";
import japao from "./japao.png";
import jordania from "./jordania.png";
import kuwait from "./kuwait.png";
import laos from "./laos.png";
import libano from "./libano.png";
import malasia from "./malasia.png";
import maldivas from "./maldivas.png";
import mongolia from "./mongolia.png";
import nepal from "./nepal.png";
import oma from "./oma.png";
import paquistao from "./paquistao.png";
import quirguistao from "./quirguistao.png";
import singapura from "./singapura.png";
import siria from "./siria.png";
import srilanka from "./srilanka.png";
import tailandia from "./tailandia.png";
import taiwan from "./taiwan.png";
import tajiquistao from "./tajiquistao.png";
import timorleste from "./timorleste.png";
import turcomenistao from "./turcomenistao.png";
import turquia from "./turquia.png";
import uzbequistao from "./uzbequistao.png";
import vietna from "./vietna.png";

export {
  afeganistao,
  arabiasaudita,
  armenia,
  azerbaijao,
  bahrein,
  bangladesh,
  birmania,
  brunei,
  butao,
  camboja,
  catar,
  cazaquistao,
  china,
  chipre,
  coreiadonorte,
  coreiadosul,
  emiradosarabesunidos,
  filipinas,
  georgia,
  iemen,
  india,
  indonesia,
  iran,
  iraque,
  israel,
  japao,
  jordania,
  kuwait,
  laos,
  libano,
  malasia,
  maldivas,
  mongolia,
  nepal,
  oma,
  paquistao,
  quirguistao,
  singapura,
  siria,
  srilanka,
  tailandia,
  taiwan,
  tajiquistao,
  timorleste,
  turcomenistao,
  turquia,
  uzbequistao,
  vietna,
};

