// THIS FILE IS AUTO GENERATED
// DO NOT EDIT MANUALLY

// GENERATED BY scripts/codegen/countries-index.mjs
// TO REGEN RUN `yarn zx scripts/codegen/countries-index.mjs`

import albania from "./albania.png";
import alemanha from "./alemanha.png";
import andorra from "./andorra.png";
import austria from "./austria.png";
import belgica from "./belgica.png";
import bielorussia from "./bielorussia.png";
import bosniaeherzegovina from "./bosniaeherzegovina.png";
import bulgaria from "./bulgaria.png";
import croacia from "./croacia.png";
import dinamarca from "./dinamarca.png";
import eslovaquia from "./eslovaquia.png";
import eslovenia from "./eslovenia.png";
import espanha from "./espanha.png";
import estonia from "./estonia.png";
import finlandia from "./finlandia.png";
import franca from "./franca.png";
import grecia from "./grecia.png";
import hungria from "./hungria.png";
import irlanda from "./irlanda.png";
import islandia from "./islandia.png";
import italia from "./italia.png";
import kosovo from "./kosovo.png";
import letonia from "./letonia.png";
import liechtenstein from "./liechtenstein.png";
import lituania from "./lituania.png";
import luxemburgo from "./luxemburgo.png";
import macedoniadonorte from "./macedoniadonorte.png";
import malta from "./malta.png";
import moldavia from "./moldavia.png";
import monaco from "./monaco.png";
import montenegro from "./montenegro.png";
import noruega from "./noruega.png";
import paisesbaixos from "./paisesbaixos.png";
import polonia from "./polonia.png";
import portugal from "./portugal.png";
import reinounido from "./reinounido.png";
import republicatcheca from "./republicatcheca.png";
import romenia from "./romenia.png";
import russia from "./russia.png";
import sanmarino from "./sanmarino.png";
import servia from "./servia.png";
import suecia from "./suecia.png";
import suica from "./suica.png";
import ucrania from "./ucrania.png";
import vaticano from "./vaticano.png";

export {
  albania,
  alemanha,
  andorra,
  austria,
  belgica,
  bielorussia,
  bosniaeherzegovina,
  bulgaria,
  croacia,
  dinamarca,
  eslovaquia,
  eslovenia,
  espanha,
  estonia,
  finlandia,
  franca,
  grecia,
  hungria,
  irlanda,
  islandia,
  italia,
  kosovo,
  letonia,
  liechtenstein,
  lituania,
  luxemburgo,
  macedoniadonorte,
  malta,
  moldavia,
  monaco,
  montenegro,
  noruega,
  paisesbaixos,
  polonia,
  portugal,
  reinounido,
  republicatcheca,
  romenia,
  russia,
  sanmarino,
  servia,
  suecia,
  suica,
  ucrania,
  vaticano,
};

