// THIS FILE IS AUTO GENERATED
// DO NOT EDIT MANUALLY

// GENERATED BY scripts/codegen/countries-index.mjs
// TO REGEN RUN `yarn zx scripts/codegen/countries-index.mjs`

import australia from "./australia.png";
import fiji from "./fiji.png";
import ilhasmarshall from "./ilhasmarshall.png";
import ilhassalomao from "./ilhassalomao.png";
import kiribati from "./kiribati.png";
import micronesia from "./micronesia.png";
import nauru from "./nauru.png";
import novazelandia from "./novazelandia.png";
import palau from "./palau.png";
import papuanovaguine from "./papuanovaguine.png";
import samoa from "./samoa.png";
import tonga from "./tonga.png";
import tuvalu from "./tuvalu.png";
import vanuatu from "./vanuatu.png";

export {
  australia,
  fiji,
  ilhasmarshall,
  ilhassalomao,
  kiribati,
  micronesia,
  nauru,
  novazelandia,
  palau,
  papuanovaguine,
  samoa,
  tonga,
  tuvalu,
  vanuatu,
};

