import * as flags from "./flags";

let _id = 0;
function id() {
  return ++_id;
}

export enum Continent {
  Africa = "Africa",
  America = "America",
  Asia = "Asia",
  Europe = "Europe",
  Oceania = "Oceania",
}

export const africa = [
  {
    id: id(),
    name: "África do Sul",
    flag: flags.africadosul,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Angola",
    flag: flags.angola,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Argélia",
    flag: flags.argelia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Benim",
    flag: flags.benim,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Botswana",
    alias: ["Botsuana"],
    flag: flags.botswana,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Burkina Faso",
    flag: flags.burkinafaso,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Burundi",
    flag: flags.burundi,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Cabo Verde",
    flag: flags.caboverde,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Camarões",
    flag: flags.camaroes,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Chade",
    flag: flags.chade,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Comores",
    flag: flags.comores,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Costa do Marfim",
    flag: flags.costadomarfim,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Djibouti",
    flag: flags.djibouti,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Egito",
    flag: flags.egito,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Eritréia",
    flag: flags.eritreia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Etiópia",
    flag: flags.etiopia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Gabão",
    flag: flags.gabao,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Gambia",
    flag: flags.gambia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Gana",
    flag: flags.gana,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Guiné-Bissau",
    flag: flags.guinebissau,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Guiné Equatorial",
    flag: flags.guineequatorial,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Guiné",
    flag: flags.guine,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Lesoto",
    flag: flags.lesoto,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Libéria",
    flag: flags.liberia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Líbia",
    flag: flags.libia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Madagascar",
    flag: flags.madagascar,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Malawi",
    flag: flags.malawi,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Mali",
    flag: flags.mali,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Marrocos",
    flag: flags.marrocos,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Maurício",
    alias: ["Maurícia", "Mauritius"],
    flag: flags.mauricia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Mauritânia",
    flag: flags.mauritania,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Moçambique",
    flag: flags.mocambique,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Namíbia",
    flag: flags.namibia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Níger",
    flag: flags.niger,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Nigéria",
    flag: flags.nigeria,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Quênia",
    flag: flags.quenia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "República Centro Africana",
    alias: ["África Central"],
    flag: flags.republicacentroafricana,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "República Democrática do Congo",
    alias: ["DR Congo", "Congo", "DROC"],
    flag: flags.republicademocraticadocongo,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "República do Congo",
    alias: ["Congo"],
    flag: flags.republicadocongo,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Ruanda",
    flag: flags.ruanda,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "São Tomé e Príncipe",
    alias: ["São Tomé"],
    flag: flags.saotomeeprincipe,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Senegal",
    flag: flags.senegal,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Serra Leoa",
    flag: flags.serraleoa,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Seychelles",
    flag: flags.seychelles,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Somália",
    flag: flags.somalia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Suazilândia",
    alias: ["Essuatíni"],
    flag: flags.suazilandia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Sudão do Sul",
    flag: flags.sudaodosul,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Sudão",
    flag: flags.sudao,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Tanzânia",
    flag: flags.tanzania,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Togo",
    flag: flags.togo,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Tunísia",
    flag: flags.tunisia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Uganda",
    flag: flags.uganda,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Zâmbia",
    flag: flags.zambia,
    continent: Continent.Africa,
  },
  {
    id: id(),
    name: "Zimbábue",
    flag: flags.zimbabue,
    continent: Continent.Africa,
  },
];

export const america = [
  {
    id: id(),
    name: "Antígua e Barbuda",
    alias: ["Antígua", "Barbuda"],
    flag: flags.antiguaebarbuda,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Argentina",
    flag: flags.argentina,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Bahamas",
    flag: flags.bahamas,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Barbados",
    flag: flags.barbados,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Belize",
    flag: flags.belize,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Bolívia",
    flag: flags.bolivia,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Brasil",
    flag: flags.brasil,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Canadá",
    flag: flags.canada,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Chile",
    flag: flags.chile,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Colômbia",
    flag: flags.colombia,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Costa Rica",
    flag: flags.costarica,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Cuba",
    flag: flags.cuba,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Dominica",
    flag: flags.dominica,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "El Salvador",
    flag: flags.elsalvador,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Equador",
    flag: flags.equador,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Estados Unidos da América",
    alias: ["Estados Unidos", "EUA"],
    flag: flags.estadosunidos,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Granada",
    flag: flags.granada,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Guatemala",
    flag: flags.guatemala,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Guiana",
    flag: flags.guiana,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Haiti",
    flag: flags.haiti,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Honduras",
    flag: flags.honduras,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Jamaica",
    flag: flags.jamaica,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "México",
    flag: flags.mexico,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Nicarágua",
    flag: flags.nicaragua,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Panamá",
    flag: flags.panama,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Paraguai",
    flag: flags.paraguai,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Peru",
    flag: flags.peru,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "República Dominicana",
    alias: ["Dominicana"],
    flag: flags.republicadominicana,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Santa Lúcia",
    flag: flags.santalucia,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "São Cristóvão e Nevis",
    alias: ["São Cristóvão", "Nevis"],
    flag: flags.saocristovaoenevis,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "São Vicente e Granadinas",
    alias: ["São Vicente", "Granadinas"],
    flag: flags.saovicenteegranadinas,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Suriname",
    flag: flags.suriname,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Trinidad e Tobago",
    alias: ["Trinidad", "Tobago"],
    flag: flags.trinidadetobago,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Uruguai",
    flag: flags.uruguai,
    continent: Continent.America,
  },
  {
    id: id(),
    name: "Venezuela",
    flag: flags.venezuela,
    continent: Continent.America,
  },
];

export const asia = [
  {
    id: id(),
    name: "Afeganistão",
    flag: flags.afeganistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Arábia Saudita",
    flag: flags.arabiasaudita,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Armênia",
    flag: flags.armenia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Azerbaijão",
    flag: flags.azerbaijao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Bahrein",
    flag: flags.bahrein,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Bangladesh",
    flag: flags.bangladesh,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Myanmar",
    alias: ["Burma", "Birmânia"],
    flag: flags.birmania,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Brunei",
    flag: flags.brunei,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Butão",
    flag: flags.butao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Camboja",
    alias: ["Cambodja"],
    flag: flags.camboja,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Catar",
    flag: flags.catar,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Cazaquistão",
    flag: flags.cazaquistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "China",
    flag: flags.china,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Chipre",
    flag: flags.chipre,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Coréia do Norte",
    flag: flags.coreiadonorte,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Coréia do Sul",
    flag: flags.coreiadosul,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Emirados Árabes Unidos",
    alias: ["EAU"],
    flag: flags.emiradosarabesunidos,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Filipinas",
    flag: flags.filipinas,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Geórgia",
    flag: flags.georgia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Iêmen",
    flag: flags.iemen,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Índia",
    flag: flags.india,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Indonésia",
    flag: flags.indonesia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Iran",
    alias: ["Irão"],
    flag: flags.iran,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Iraque",
    flag: flags.iraque,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Israel",
    flag: flags.israel,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Japão",
    flag: flags.japao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Jordânia",
    alias: ["Reino Haxemita da Jordânia"],
    flag: flags.jordania,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Kuwait",
    alias: ["Kuaite", "Cuaite"],
    flag: flags.kuwait,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Laos",
    flag: flags.laos,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Líbano",
    flag: flags.libano,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Malásia",
    flag: flags.malasia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Maldivas",
    flag: flags.maldivas,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Mongólia",
    flag: flags.mongolia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Nepal",
    flag: flags.nepal,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Omã",
    alias: ["Omão", "Sultanato de Omã"],
    flag: flags.oma,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Paquistão",
    flag: flags.paquistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Quirguistão",
    alias: ["Quirguizistão", "Quirguízia", "República Quirguiz"],
    flag: flags.quirguistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Singapura",
    flag: flags.singapura,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Síria",
    flag: flags.siria,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Sri Lanka",
    flag: flags.srilanka,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Tailândia",
    flag: flags.tailandia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Taiwan",
    flag: flags.taiwan,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Tajiquistão",
    alias: ["Tadjiquistão"],
    flag: flags.tajiquistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Timor-Leste",
    flag: flags.timorleste,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Turcomenistão",
    alias: ["Turquemenistão"],
    flag: flags.turcomenistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Turquia",
    flag: flags.turquia,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Uzbequistão",
    alias: ["Usbequistão"],
    flag: flags.uzbequistao,
    continent: Continent.Asia,
  },
  {
    id: id(),
    name: "Vietnã",
    alias: ["Vietname"],
    flag: flags.vietna,
    continent: Continent.Asia,
  },
];

export const europe = [
  {
    id: id(),
    name: "Albânia",
    flag: flags.albania,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Alemanha",
    flag: flags.alemanha,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Andorra",
    flag: flags.andorra,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Áustria",
    flag: flags.austria,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Bélgica",
    flag: flags.belgica,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Belarus",
    alias: ["Bielorússia"],
    flag: flags.bielorussia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Bósnia e Herzegovina",
    alias: ["Bósnia", "Herzegovina"],
    flag: flags.bosniaeherzegovina,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Bulgária",
    flag: flags.bulgaria,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Croácia",
    flag: flags.croacia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Dinamarca",
    flag: flags.dinamarca,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Eslováquia",
    flag: flags.eslovaquia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Eslovênia",
    flag: flags.eslovenia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Espanha",
    flag: flags.espanha,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Estônia",
    flag: flags.estonia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Finlândia",
    flag: flags.finlandia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "França",
    flag: flags.franca,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Grécia",
    flag: flags.grecia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Hungria",
    flag: flags.hungria,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Irlanda",
    flag: flags.irlanda,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Islândia",
    flag: flags.islandia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Itália",
    flag: flags.italia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Kosovo",
    flag: flags.kosovo,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Letônia",
    flag: flags.letonia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Liechtenstein",
    flag: flags.liechtenstein,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Lituânia",
    flag: flags.lituania,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Luxemburgo",
    flag: flags.luxemburgo,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Macedônia do Norte",
    alias: ["Macedonia"],
    flag: flags.macedoniadonorte,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Malta",
    flag: flags.malta,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Moldávia",
    flag: flags.moldavia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Mônaco",
    flag: flags.monaco,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Montenegro",
    flag: flags.montenegro,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Noruega",
    flag: flags.noruega,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Países Baixos",
    alias: ["Holanda"],
    flag: flags.paisesbaixos,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Polônia",
    flag: flags.polonia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Portugal",
    flag: flags.portugal,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Reino Unido",
    flag: flags.reinounido,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "República Tcheca",
    alias: ["Chéquia", "Tchéquia", "Tcheca"],
    flag: flags.republicatcheca,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Romênia",
    flag: flags.romenia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Rússia",
    flag: flags.russia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "San Marino",
    alias: ["São Marino", "São Marinho"],
    flag: flags.sanmarino,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Sérvia",
    flag: flags.servia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Suécia",
    flag: flags.suecia,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Suíça",
    flag: flags.suica,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Ucrânia",
    flag: flags.ucrania,
    continent: Continent.Europe,
  },
  {
    id: id(),
    name: "Vaticano",
    flag: flags.vaticano,
    continent: Continent.Europe,
  },
];

export const oceania = [
  {
    id: id(),
    name: "Austrália",
    flag: flags.australia,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Fiji",
    alias: ["Ilhas Fiji"],
    flag: flags.fiji,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Ilhas Marshall",
    alias: ["Marshall"],
    flag: flags.ilhasmarshall,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Ilhas Salomão",
    alias: ["Salomão"],
    flag: flags.ilhassalomao,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Kiribati",
    alias: ["Quiribati"],
    flag: flags.kiribati,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Estados Federados da Micronésia",
    alias: ["Micronésia", "EFM"],
    flag: flags.micronesia,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Nauru",
    flag: flags.nauru,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Nova Zelândia",
    flag: flags.novazelandia,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Palau",
    flag: flags.palau,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Papua-Nova Guiné",
    alias: ["Papuásia-Nova Guiné"],
    flag: flags.papuanovaguine,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Samoa",
    flag: flags.samoa,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Tonga",
    flag: flags.tonga,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Tuvalu",
    flag: flags.tuvalu,
    continent: Continent.Oceania,
  },
  {
    id: id(),
    name: "Vanuatu",
    flag: flags.vanuatu,
    continent: Continent.Oceania,
  },
];

export const countries = [...africa, ...america, ...asia, ...europe, ...oceania];
export const all = [...africa, ...america, ...asia, ...europe, ...oceania];

export type Country = typeof all[number];
