import * as flags from "./flags";
import * as enums from "./enums";

export const countries = [
  {
    id: "ZA",
    name: "África do Sul",
    flag: flags.ZA,
    continent: enums.Continent.Africa,
  },
  {
    id: "AO",
    name: "Angola",
    flag: flags.AO,
    continent: enums.Continent.Africa,
  },
  {
    id: "DZ",
    name: "Argélia",
    flag: flags.DZ,
    continent: enums.Continent.Africa,
  },
  {
    id: "BJ",
    name: "Benim",
    flag: flags.BJ,
    continent: enums.Continent.Africa,
  },
  {
    id: "BW",
    name: "Botswana",
    alias: ["Botsuana"],
    flag: flags.BW,
    continent: enums.Continent.Africa,
  },
  {
    id: "BF",
    name: "Burkina Faso",
    flag: flags.BF,
    continent: enums.Continent.Africa,
  },
  {
    id: "BI",
    name: "Burundi",
    flag: flags.BI,
    continent: enums.Continent.Africa,
  },
  {
    id: "CV",
    name: "Cabo Verde",
    flag: flags.CV,
    continent: enums.Continent.Africa,
  },
  {
    id: "CM",
    name: "Camarões",
    flag: flags.CM,
    continent: enums.Continent.Africa,
  },
  {
    id: "TD",
    name: "Chade",
    flag: flags.TD,
    continent: enums.Continent.Africa,
  },
  {
    id: "KM",
    name: "Comores",
    flag: flags.KM,
    continent: enums.Continent.Africa,
  },
  {
    id: "CI",
    name: "Costa do Marfim",
    flag: flags.CI,
    continent: enums.Continent.Africa,
  },
  {
    id: "DJ",
    name: "Djibouti",
    flag: flags.DJ,
    continent: enums.Continent.Africa,
  },
  {
    id: "EG",
    name: "Egito",
    flag: flags.EG,
    continent: enums.Continent.Africa,
  },
  {
    id: "ER",
    name: "Eritréia",
    flag: flags.ER,
    continent: enums.Continent.Africa,
  },
  {
    id: "ET",
    name: "Etiópia",
    flag: flags.ET,
    continent: enums.Continent.Africa,
  },
  {
    id: "GA",
    name: "Gabão",
    flag: flags.GA,
    continent: enums.Continent.Africa,
  },
  {
    id: "GM",
    name: "Gâmbia",
    flag: flags.GM,
    continent: enums.Continent.Africa,
  },
  {
    id: "GH",
    name: "Gana",
    flag: flags.GH,
    continent: enums.Continent.Africa,
  },
  {
    id: "GW",
    name: "Guiné-Bissau",
    flag: flags.GW,
    continent: enums.Continent.Africa,
  },
  {
    id: "GQ",
    name: "Guiné Equatorial",
    flag: flags.GQ,
    continent: enums.Continent.Africa,
  },
  {
    id: "GN",
    name: "Guiné",
    flag: flags.GN,
    continent: enums.Continent.Africa,
  },
  {
    id: "LS",
    name: "Lesoto",
    flag: flags.LS,
    continent: enums.Continent.Africa,
  },
  {
    id: "LR",
    name: "Libéria",
    flag: flags.LR,
    continent: enums.Continent.Africa,
  },
  {
    id: "LY",
    name: "Líbia",
    flag: flags.LY,
    continent: enums.Continent.Africa,
  },
  {
    id: "MG",
    name: "Madagascar",
    flag: flags.MG,
    continent: enums.Continent.Africa,
  },
  {
    id: "MW",
    name: "Malawi",
    flag: flags.MW,
    continent: enums.Continent.Africa,
  },
  {
    id: "ML",
    name: "Mali",
    flag: flags.ML,
    continent: enums.Continent.Africa,
  },
  {
    id: "MA",
    name: "Marrocos",
    flag: flags.MA,
    continent: enums.Continent.Africa,
  },
  {
    id: "MU",
    name: "Maurício",
    alias: ["Maurícia", "Mauritius"],
    flag: flags.MU,
    continent: enums.Continent.Africa,
  },
  {
    id: "MR",
    name: "Mauritânia",
    flag: flags.MR,
    continent: enums.Continent.Africa,
  },
  {
    id: "MZ",
    name: "Moçambique",
    flag: flags.MZ,
    continent: enums.Continent.Africa,
  },
  {
    id: "NA",
    name: "Namíbia",
    flag: flags.NA,
    continent: enums.Continent.Africa,
  },
  {
    id: "NE",
    name: "Níger",
    flag: flags.NE,
    continent: enums.Continent.Africa,
  },
  {
    id: "NG",
    name: "Nigéria",
    flag: flags.NG,
    continent: enums.Continent.Africa,
  },
  {
    id: "KE",
    name: "Quênia",
    flag: flags.KE,
    continent: enums.Continent.Africa,
  },
  {
    id: "CF",
    name: "República Centro Africana",
    alias: ["África Central"],
    flag: flags.CF,
    continent: enums.Continent.Africa,
  },
  {
    id: "CD",
    name: "República Democrática do Congo",
    alias: ["DR Congo", "Congo", "DROC"],
    flag: flags.CD,
    continent: enums.Continent.Africa,
  },
  {
    id: "CG",
    name: "República do Congo",
    alias: ["Congo"],
    flag: flags.CG,
    continent: enums.Continent.Africa,
  },
  {
    id: "RW",
    name: "Ruanda",
    flag: flags.RW,
    continent: enums.Continent.Africa,
  },
  {
    id: "ST",
    name: "São Tomé e Príncipe",
    alias: ["São Tomé"],
    flag: flags.ST,
    continent: enums.Continent.Africa,
  },
  {
    id: "SN",
    name: "Senegal",
    flag: flags.SN,
    continent: enums.Continent.Africa,
  },
  {
    id: "SL",
    name: "Serra Leoa",
    flag: flags.SL,
    continent: enums.Continent.Africa,
  },
  {
    id: "SC",
    name: "Seychelles",
    flag: flags.SC,
    continent: enums.Continent.Africa,
  },
  {
    id: "SO",
    name: "Somália",
    flag: flags.SO,
    continent: enums.Continent.Africa,
  },
  {
    id: "SZ",
    name: "Suazilândia",
    alias: ["Essuatíni"],
    flag: flags.SZ,
    continent: enums.Continent.Africa,
  },
  {
    id: "SS",
    name: "Sudão do Sul",
    flag: flags.SS,
    continent: enums.Continent.Africa,
  },
  {
    id: "SD",
    name: "Sudão",
    flag: flags.SD,
    continent: enums.Continent.Africa,
  },
  {
    id: "TZ",
    name: "Tanzânia",
    flag: flags.TZ,
    continent: enums.Continent.Africa,
  },
  {
    id: "TG",
    name: "Togo",
    flag: flags.TG,
    continent: enums.Continent.Africa,
  },
  {
    id: "TN",
    name: "Tunísia",
    flag: flags.TN,
    continent: enums.Continent.Africa,
  },
  {
    id: "UG",
    name: "Uganda",
    flag: flags.UG,
    continent: enums.Continent.Africa,
  },
  {
    id: "ZM",
    name: "Zâmbia",
    flag: flags.ZM,
    continent: enums.Continent.Africa,
  },
  {
    id: "ZW",
    name: "Zimbábue",
    flag: flags.ZW,
    continent: enums.Continent.Africa,
  },
  {
    id: "AG",
    name: "Antígua e Barbuda",
    alias: ["Antígua", "Barbuda"],
    flag: flags.AG,
    continent: enums.Continent.America,
  },
  {
    id: "AR",
    name: "Argentina",
    flag: flags.AR,
    continent: enums.Continent.America,
  },
  {
    id: "BS",
    name: "Bahamas",
    flag: flags.BS,
    continent: enums.Continent.America,
  },
  {
    id: "BB",
    name: "Barbados",
    flag: flags.BB,
    continent: enums.Continent.America,
  },
  {
    id: "BZ",
    name: "Belize",
    flag: flags.BZ,
    continent: enums.Continent.America,
  },
  {
    id: "BO",
    name: "Bolívia",
    flag: flags.BO,
    continent: enums.Continent.America,
  },
  {
    id: "BR",
    name: "Brasil",
    flag: flags.BR,
    continent: enums.Continent.America,
  },
  {
    id: "CA",
    name: "Canadá",
    flag: flags.CA,
    continent: enums.Continent.America,
  },
  {
    id: "CL",
    name: "Chile",
    flag: flags.CL,
    continent: enums.Continent.America,
  },
  {
    id: "CO",
    name: "Colômbia",
    flag: flags.CO,
    continent: enums.Continent.America,
  },
  {
    id: "CR",
    name: "Costa Rica",
    flag: flags.CR,
    continent: enums.Continent.America,
  },
  {
    id: "CU",
    name: "Cuba",
    flag: flags.CU,
    continent: enums.Continent.America,
  },
  {
    id: "DM",
    name: "Dominica",
    flag: flags.DM,
    continent: enums.Continent.America,
  },
  {
    id: "SV",
    name: "El Salvador",
    flag: flags.SV,
    continent: enums.Continent.America,
  },
  {
    id: "EC",
    name: "Equador",
    flag: flags.EC,
    continent: enums.Continent.America,
  },
  {
    id: "US",
    name: "Estados Unidos da América",
    alias: ["Estados Unidos", "EUA"],
    flag: flags.US,
    continent: enums.Continent.America,
  },
  {
    id: "GD",
    name: "Granada",
    flag: flags.GD,
    continent: enums.Continent.America,
  },
  {
    id: "GT",
    name: "Guatemala",
    flag: flags.GT,
    continent: enums.Continent.America,
  },
  {
    id: "GY",
    name: "Guiana",
    flag: flags.GY,
    continent: enums.Continent.America,
  },
  {
    id: "HT",
    name: "Haiti",
    flag: flags.HT,
    continent: enums.Continent.America,
  },
  {
    id: "HN",
    name: "Honduras",
    flag: flags.HN,
    continent: enums.Continent.America,
  },
  {
    id: "JM",
    name: "Jamaica",
    flag: flags.JM,
    continent: enums.Continent.America,
  },
  {
    id: "MX",
    name: "México",
    flag: flags.MX,
    continent: enums.Continent.America,
  },
  {
    id: "NI",
    name: "Nicarágua",
    flag: flags.NI,
    continent: enums.Continent.America,
  },
  {
    id: "PA",
    name: "Panamá",
    flag: flags.PA,
    continent: enums.Continent.America,
  },
  {
    id: "PY",
    name: "Paraguai",
    flag: flags.PY,
    continent: enums.Continent.America,
  },
  {
    id: "PE",
    name: "Peru",
    flag: flags.PE,
    continent: enums.Continent.America,
  },
  {
    id: "DO",
    name: "República Dominicana",
    alias: ["Dominicana"],
    flag: flags.DO,
    continent: enums.Continent.America,
  },
  {
    id: "LC",
    name: "Santa Lúcia",
    flag: flags.LC,
    continent: enums.Continent.America,
  },
  {
    id: "KN",
    name: "São Cristóvão e Nevis",
    alias: ["São Cristóvão", "Nevis"],
    flag: flags.KN,
    continent: enums.Continent.America,
  },
  {
    id: "VC",
    name: "São Vicente e Granadinas",
    alias: ["São Vicente", "Granadinas"],
    flag: flags.VC,
    continent: enums.Continent.America,
  },
  {
    id: "SR",
    name: "Suriname",
    flag: flags.SR,
    continent: enums.Continent.America,
  },
  {
    id: "TT",
    name: "Trinidad e Tobago",
    alias: ["Trinidad", "Tobago"],
    flag: flags.TT,
    continent: enums.Continent.America,
  },
  {
    id: "UY",
    name: "Uruguai",
    flag: flags.UY,
    continent: enums.Continent.America,
  },
  {
    id: "VE",
    name: "Venezuela",
    flag: flags.VE,
    continent: enums.Continent.America,
  },
  {
    id: "AF",
    name: "Afeganistão",
    flag: flags.AF,
    continent: enums.Continent.Asia,
  },
  {
    id: "SA",
    name: "Arábia Saudita",
    flag: flags.SA,
    continent: enums.Continent.Asia,
  },
  {
    id: "AM",
    name: "Armênia",
    flag: flags.AM,
    continent: enums.Continent.Asia,
  },
  {
    id: "AZ",
    name: "Azerbaijão",
    flag: flags.AZ,
    continent: enums.Continent.Asia,
  },
  {
    id: "BH",
    name: "Bahrein",
    alias: ["Barém", "Barein", "Bareine"],
    flag: flags.BH,
    continent: enums.Continent.Asia,
  },
  {
    id: "BD",
    name: "Bangladesh",
    flag: flags.BD,
    continent: enums.Continent.Asia,
  },
  {
    id: "MM",
    name: "Myanmar",
    alias: ["Burma", "Birmânia"],
    flag: flags.MM,
    continent: enums.Continent.Asia,
  },
  {
    id: "BN",
    name: "Brunei",
    alias: ["Darussalam", "Darussalã"],
    flag: flags.BN,
    continent: enums.Continent.Asia,
  },
  {
    id: "BT",
    name: "Butão",
    flag: flags.BT,
    continent: enums.Continent.Asia,
  },
  {
    id: "KH",
    name: "Camboja",
    alias: ["Cambodja"],
    flag: flags.KH,
    continent: enums.Continent.Asia,
  },
  {
    id: "QA",
    name: "Catar",
    flag: flags.QA,
    continent: enums.Continent.Asia,
  },
  {
    id: "KZ",
    name: "Cazaquistão",
    flag: flags.KZ,
    continent: enums.Continent.Asia,
  },
  {
    id: "CN",
    name: "China",
    flag: flags.CN,
    continent: enums.Continent.Asia,
  },
  {
    id: "CY",
    name: "Chipre",
    flag: flags.CY,
    continent: enums.Continent.Asia,
  },
  {
    id: "KP",
    name: "Coréia do Norte",
    flag: flags.KP,
    continent: enums.Continent.Asia,
  },
  {
    id: "KR",
    name: "Coréia do Sul",
    flag: flags.KR,
    continent: enums.Continent.Asia,
  },
  {
    id: "AE",
    name: "Emirados Árabes Unidos",
    alias: ["EAU"],
    flag: flags.AE,
    continent: enums.Continent.Asia,
  },
  {
    id: "PH",
    name: "Filipinas",
    flag: flags.PH,
    continent: enums.Continent.Asia,
  },
  {
    id: "GE",
    name: "Geórgia",
    flag: flags.GE,
    continent: enums.Continent.Asia,
  },
  {
    id: "YE",
    name: "Iêmen",
    flag: flags.YE,
    continent: enums.Continent.Asia,
  },
  {
    id: "IN",
    name: "Índia",
    flag: flags.IN,
    continent: enums.Continent.Asia,
  },
  {
    id: "ID",
    name: "Indonésia",
    flag: flags.ID,
    continent: enums.Continent.Asia,
  },
  {
    id: "IR",
    name: "Iran",
    alias: ["Irão"],
    flag: flags.IR,
    continent: enums.Continent.Asia,
  },
  {
    id: "IQ",
    name: "Iraque",
    flag: flags.IQ,
    continent: enums.Continent.Asia,
  },
  {
    id: "IL",
    name: "Israel",
    flag: flags.IL,
    continent: enums.Continent.Asia,
  },
  {
    id: "JP",
    name: "Japão",
    flag: flags.JP,
    continent: enums.Continent.Asia,
  },
  {
    id: "JO",
    name: "Jordânia",
    alias: ["Reino Haxemita da Jordânia"],
    flag: flags.JO,
    continent: enums.Continent.Asia,
  },
  {
    id: "KW",
    name: "Kuwait",
    alias: ["Kuaite", "Cuaite"],
    flag: flags.KW,
    continent: enums.Continent.Asia,
  },
  {
    id: "LA",
    name: "Laos",
    flag: flags.LA,
    continent: enums.Continent.Asia,
  },
  {
    id: "LB",
    name: "Líbano",
    flag: flags.LB,
    continent: enums.Continent.Asia,
  },
  {
    id: "MY",
    name: "Malásia",
    flag: flags.MY,
    continent: enums.Continent.Asia,
  },
  {
    id: "MV",
    name: "Maldivas",
    flag: flags.MV,
    continent: enums.Continent.Asia,
  },
  {
    id: "MN",
    name: "Mongólia",
    flag: flags.MN,
    continent: enums.Continent.Asia,
  },
  {
    id: "NP",
    name: "Nepal",
    flag: flags.NP,
    continent: enums.Continent.Asia,
  },
  {
    id: "OM",
    name: "Omã",
    alias: ["Omão", "Sultanato de Omã"],
    flag: flags.OM,
    continent: enums.Continent.Asia,
  },
  {
    id: "PK",
    name: "Paquistão",
    flag: flags.PK,
    continent: enums.Continent.Asia,
  },
  {
    id: "KG",
    name: "Quirguistão",
    alias: ["Quirguizistão", "Quirguízia", "República Quirguiz"],
    flag: flags.KG,
    continent: enums.Continent.Asia,
  },
  {
    id: "SG",
    name: "Singapura",
    flag: flags.SG,
    continent: enums.Continent.Asia,
  },
  {
    id: "SY",
    name: "Síria",
    flag: flags.SY,
    continent: enums.Continent.Asia,
  },
  {
    id: "LK",
    name: "Sri Lanka",
    flag: flags.LK,
    continent: enums.Continent.Asia,
  },
  {
    id: "TH",
    name: "Tailândia",
    flag: flags.TH,
    continent: enums.Continent.Asia,
  },
  {
    id: "TW",
    name: "Taiwan",
    flag: flags.TW,
    continent: enums.Continent.Asia,
  },
  {
    id: "TJ",
    name: "Tajiquistão",
    alias: ["Tadjiquistão"],
    flag: flags.TJ,
    continent: enums.Continent.Asia,
  },
  {
    id: "TL",
    name: "Timor-Leste",
    flag: flags.TL,
    continent: enums.Continent.Asia,
  },
  {
    id: "TM",
    name: "Turcomenistão",
    alias: ["Turquemenistão"],
    flag: flags.TM,
    continent: enums.Continent.Asia,
  },
  {
    id: "TR",
    name: "Turquia",
    flag: flags.TR,
    continent: enums.Continent.Asia,
  },
  {
    id: "UZ",
    name: "Uzbequistão",
    alias: ["Usbequistão"],
    flag: flags.UZ,
    continent: enums.Continent.Asia,
  },
  {
    id: "VN",
    name: "Vietnã",
    alias: ["Vietname"],
    flag: flags.VN,
    continent: enums.Continent.Asia,
  },
  {
    id: "AL",
    name: "Albânia",
    flag: flags.AL,
    continent: enums.Continent.Europe,
  },
  {
    id: "DE",
    name: "Alemanha",
    flag: flags.DE,
    continent: enums.Continent.Europe,
  },
  {
    id: "AD",
    name: "Andorra",
    flag: flags.AD,
    continent: enums.Continent.Europe,
  },
  {
    id: "AT",
    name: "Áustria",
    flag: flags.AT,
    continent: enums.Continent.Europe,
  },
  {
    id: "BE",
    name: "Bélgica",
    flag: flags.BE,
    continent: enums.Continent.Europe,
  },
  {
    id: "BY",
    name: "Belarus",
    alias: ["Bielorússia"],
    flag: flags.BY,
    continent: enums.Continent.Europe,
  },
  {
    id: "BA",
    name: "Bósnia e Herzegovina",
    alias: ["Bósnia", "Herzegovina"],
    flag: flags.BA,
    continent: enums.Continent.Europe,
  },
  {
    id: "BG",
    name: "Bulgária",
    flag: flags.BG,
    continent: enums.Continent.Europe,
  },
  {
    id: "HR",
    name: "Croácia",
    flag: flags.HR,
    continent: enums.Continent.Europe,
  },
  {
    id: "DK",
    name: "Dinamarca",
    flag: flags.DK,
    continent: enums.Continent.Europe,
  },
  {
    id: "SK",
    name: "Eslováquia",
    flag: flags.SK,
    continent: enums.Continent.Europe,
  },
  {
    id: "SI",
    name: "Eslovênia",
    flag: flags.SI,
    continent: enums.Continent.Europe,
  },
  {
    id: "ES",
    name: "Espanha",
    flag: flags.ES,
    continent: enums.Continent.Europe,
  },
  {
    id: "EE",
    name: "Estônia",
    flag: flags.EE,
    continent: enums.Continent.Europe,
  },
  {
    id: "FI",
    name: "Finlândia",
    flag: flags.FI,
    continent: enums.Continent.Europe,
  },
  {
    id: "FR",
    name: "França",
    flag: flags.FR,
    continent: enums.Continent.Europe,
  },
  {
    id: "GR",
    name: "Grécia",
    flag: flags.GR,
    continent: enums.Continent.Europe,
  },
  {
    id: "HU",
    name: "Hungria",
    flag: flags.HU,
    continent: enums.Continent.Europe,
  },
  {
    id: "IE",
    name: "Irlanda",
    flag: flags.IE,
    continent: enums.Continent.Europe,
  },
  {
    id: "IS",
    name: "Islândia",
    flag: flags.IS,
    continent: enums.Continent.Europe,
  },
  {
    id: "IT",
    name: "Itália",
    flag: flags.IT,
    continent: enums.Continent.Europe,
  },
  {
    id: "XK",
    name: "Kosovo",
    flag: flags.XK,
    continent: enums.Continent.Europe,
  },
  {
    id: "LV",
    name: "Letônia",
    flag: flags.LV,
    continent: enums.Continent.Europe,
  },
  {
    id: "LI",
    name: "Liechtenstein",
    flag: flags.LI,
    continent: enums.Continent.Europe,
  },
  {
    id: "LT",
    name: "Lituânia",
    flag: flags.LT,
    continent: enums.Continent.Europe,
  },
  {
    id: "LU",
    name: "Luxemburgo",
    flag: flags.LU,
    continent: enums.Continent.Europe,
  },
  {
    id: "MK",
    name: "Macedônia do Norte",
    alias: ["Macedonia"],
    flag: flags.MK,
    continent: enums.Continent.Europe,
  },
  {
    id: "MT",
    name: "Malta",
    flag: flags.MT,
    continent: enums.Continent.Europe,
  },
  {
    id: "MD",
    name: "Moldávia",
    flag: flags.MD,
    continent: enums.Continent.Europe,
  },
  {
    id: "MC",
    name: "Mônaco",
    flag: flags.MC,
    continent: enums.Continent.Europe,
  },
  {
    id: "ME",
    name: "Montenegro",
    flag: flags.ME,
    continent: enums.Continent.Europe,
  },
  {
    id: "NO",
    name: "Noruega",
    flag: flags.NO,
    continent: enums.Continent.Europe,
  },
  {
    id: "NL",
    name: "Países Baixos",
    alias: ["Holanda"],
    flag: flags.NL,
    continent: enums.Continent.Europe,
  },
  {
    id: "PL",
    name: "Polônia",
    flag: flags.PL,
    continent: enums.Continent.Europe,
  },
  {
    id: "PT",
    name: "Portugal",
    flag: flags.PT,
    continent: enums.Continent.Europe,
  },
  {
    id: "UK",
    name: "Reino Unido",
    flag: flags.UK,
    continent: enums.Continent.Europe,
  },
  {
    id: "CZ",
    name: "República Tcheca",
    alias: ["Chéquia", "Tchéquia", "Tcheca"],
    flag: flags.CZ,
    continent: enums.Continent.Europe,
  },
  {
    id: "RO",
    name: "Romênia",
    flag: flags.RO,
    continent: enums.Continent.Europe,
  },
  {
    id: "RU",
    name: "Rússia",
    flag: flags.RU,
    continent: enums.Continent.Europe,
  },
  {
    id: "SM",
    name: "San Marino",
    alias: ["São Marino", "São Marinho"],
    flag: flags.SM,
    continent: enums.Continent.Europe,
  },
  {
    id: "RS",
    name: "Sérvia",
    flag: flags.RS,
    continent: enums.Continent.Europe,
  },
  {
    id: "SE",
    name: "Suécia",
    flag: flags.SE,
    continent: enums.Continent.Europe,
  },
  {
    id: "CH",
    name: "Suíça",
    flag: flags.CH,
    continent: enums.Continent.Europe,
  },
  {
    id: "UA",
    name: "Ucrânia",
    flag: flags.UA,
    continent: enums.Continent.Europe,
  },
  {
    id: "VA",
    name: "Vaticano",
    flag: flags.VA,
    continent: enums.Continent.Europe,
  },
  {
    id: "AU",
    name: "Austrália",
    flag: flags.AU,
    continent: enums.Continent.Oceania,
  },
  {
    id: "FJ",
    name: "Fiji",
    alias: ["Ilhas Fiji"],
    flag: flags.FJ,
    continent: enums.Continent.Oceania,
  },
  {
    id: "MH",
    name: "Ilhas Marshall",
    alias: ["Marshall"],
    flag: flags.MH,
    continent: enums.Continent.Oceania,
  },
  {
    id: "SB",
    name: "Ilhas Salomão",
    alias: ["Salomão"],
    flag: flags.SB,
    continent: enums.Continent.Oceania,
  },
  {
    id: "KI",
    name: "Kiribati",
    alias: ["Quiribati"],
    flag: flags.KI,
    continent: enums.Continent.Oceania,
  },
  {
    id: "FM",
    name: "Estados Federados da Micronésia",
    alias: ["Micronésia", "EFM"],
    flag: flags.FM,
    continent: enums.Continent.Oceania,
  },
  {
    id: "NR",
    name: "Nauru",
    flag: flags.NR,
    continent: enums.Continent.Oceania,
  },
  {
    id: "NZ",
    name: "Nova Zelândia",
    flag: flags.NZ,
    continent: enums.Continent.Oceania,
  },
  {
    id: "PW",
    name: "Palau",
    flag: flags.PW,
    continent: enums.Continent.Oceania,
  },
  {
    id: "PG",
    name: "Papua-Nova Guiné",
    alias: ["Papuásia-Nova Guiné"],
    flag: flags.PG,
    continent: enums.Continent.Oceania,
  },
  {
    id: "WS",
    name: "Samoa",
    flag: flags.WS,
    continent: enums.Continent.Oceania,
  },
  {
    id: "TO",
    name: "Tonga",
    flag: flags.TO,
    continent: enums.Continent.Oceania,
  },
  {
    id: "TV",
    name: "Tuvalu",
    flag: flags.TV,
    continent: enums.Continent.Oceania,
  },
  {
    id: "VU",
    name: "Vanuatu",
    flag: flags.VU,
    continent: enums.Continent.Oceania,
  },
];

export type Country = typeof countries[number];
