import "zx/globals";
import prettier from "prettier";
import chalk from "chalk";

$.verbose = false;

const folders = ["africa", "asia", "europe", "america", "oceania"];

for (const folder of folders) {
  const ls = await $`ls src/countries/${folder}`;

  const files = ls.stdout
    .split("\n")
    .filter(Boolean)
    .filter((c) => c.endsWith(".png"))
    .map((c) => c.slice(0, -".png".length));

  const template = prettier.format(
    `
    // THIS FILE IS AUTO GENERATED
    // DO NOT EDIT MANUALLY

    // GENERATED BY scripts/codegen/countries-index.mjs
    // TO REGEN RUN \`yarn zx scripts/codegen/countries-index.mjs\`

    ${files.map((file) => `import ${file} from "./${file}.png";`).join("\n")}

    export { ${files.join(", ")} }
  `,
    {
      parser: "typescript",
    }
  );

  await $`touch src/countries/${folder}/index.ts`;
  await $`echo ${template} > src/countries/${folder}/index.ts`;
  console.log(chalk.green(`${chalk.bold("Generated:")} src/countries/${folder}/index.ts`));
}
